run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: ""

linters:
  # Disable all linters by default.
  disable-all: true
  fast: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - mnd
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - octalLiteral
      - whyNoLint
      - rangeExprCopy
      - rangeValCopy

  gosec:
    excludes:
      - G601

  errcheck:
    check-type-assertions: true # Default: false
    check-blank: true # Default: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  funlen:
    lines: -1
    statements: 50

  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "24"
      - "60"
      - "100"
      - "256"
      - "1024"
    ignored-functions:
      - strings.SplitN

  gocyclo:
    min-complexity: 15

  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"

  govet:
    disable:
      - fieldalignment
  lll:
    line-length: 100

  misspell:
    locale: US

  nakedret:
    max-func-lines: 1

  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: true

  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter

  stylecheck:
    checks: ["all", "-ST1003"]

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab
  exhaustive:
    default-signifies-exhaustive: true

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - mnd
        - lll
        - revive
        - unparam
