name: Quality control

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch source code"
        uses: actions/checkout@v4

      - name: Install Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: "Unit tests"
        run: |
          go test -v -race -count 1 -covermode atomic -coverprofile=coverage.out ./...

      - name: "Upload coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage.out

  consistency-checks:
    name: "Code Consistency Checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need to do comparisons against the main branch.

      - name: Install Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: "go.mod and go.sum consistency check"
        run: |
          go mod tidy
          if [[ -n "$(git status --porcelain)" ]]; then
            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
            exit 1
          fi

      - name: "Code consistency checks"
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          skip-cache: true
          args: -v
